### ISSUE TITLE
Use `canBeEnabled` or `canBeDisabled` for all config

### ISSUE THREAD

**Issue by Nyholm** [ekino/EkinoNewRelicBundle#156]
Such as `log_exceptions`, `log_commands`, `log_logs` etc...

Also "log_logs"??

**Comment by jderusse** [comment]
`log_logs` already use `canBeEnabled`.

Beware with `canBenEnabled` as null value is treat like `enabled`, it make sens when the config exposes an object with sub properties. But for a single items, does it make sens?

I neither don' like the name `log_logs`. `log_` prefix to be consistent with other configurations, and logs because actually they are logs.... I thought about `log_errors` but it could be confusing with `log_exceptions` and php errors... Maybe we can change the prefix by `report_` or `throws_`.. What do you think?

**Comment by Nyholm** [comment]
This issue was addressed in #155. 

For the record: `log_logs` => `monolog`. 
We decided to drop the `logs_` prefix on all config keys.
